### ISSUE TITLE
Support PROCEDURE along with FUNCTION

### ISSUE THREAD

**Issue by quantori-pokidovea** [jackscodemonkey/sphinx-sql#11]
Could you please support a PROCEDURE object type. It is quite the same as FUNCTION, but without return type

**Comment by jackscodemonkey** [comment]
I'll try to make some time in the next few days to look at it. It shouldn't be too difficult to add.

**Comment by jackscodemonkey** [comment]
Support for PROCEDURE added. Version 1.3.4 has been published to pypi.
