### ISSUE TITLE
Problem reading Postgresql dump

### ISSUE THREAD

**Issue by ClausBoHansen** [jackscodemonkey/sphinx-sql#7]
Hi,
I'm trying to auto document a database in Sphinx, including descriptions.
The example input file is created with:
pg_dump.exe -U postgres --schema-only  --table=films --file=test.sql

The resulting file is (added .TXT to be able to upload):
[test .sql.TXT](https://github.com/jackscodemonkey/sphinx-sql/files/6583911/test.sql.TXT)

Sphinx reads the file OK, but does not include any columns or descriptions.

Any help is most appreciated.

Thanks.

**Comment by jackscodemonkey** [comment]
Hi @ClausBoHansen, it looks like the extra meta info from pg_dump is interfering with the function that parses the column info. If you remove the comments and set commands above the create table line in your example file it finds the column attributes. My dev/test cases never assumed the file was generated by a backup. I'll look into filtering out the pg_dump meta info for the next release.

**Comment by ClausBoHansen** [comment]
Hi,
Thanks for looking into this.
When I remove the meta information lines, it works.
Best regards, Sbo

**Comment by jackscodemonkey** [comment]
Fixed in 1.3.1
